### ISSUE TITLE
Rendering Transfrom dealing code is in absolute mess

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#110]
`VisualComponent::VisualAttributes` builds up a partial abstraction on `TransformComponent`.
In the rendering code at times this abstraction is used, other times `TrasformComponent` is accessed directly.
The abstraction should be completed and be used everywhere in rendering code instead of accessing `TransformComponent`

**Comment by IronicallySerious** [comment]
I say get rid of `VisualComponentAttributes` completely

**Comment by sin3point14** [comment]
Now that I am writing the code for double buffering, I think that we do need some sort of abstraction in `VisualComponent` that allows access to the `RenderingBuffer` as `TransfromComponent` doesn't allow any access to it. I currently have added the relevant functions in `VisualComponentAttributes`. 
So one thing that could be done is to rename it to something like `RenderingBuffer` and remove all unrelated stuff out of it
