### ISSUE TITLE
ScriptSystem is destroyed before PhysicsSystem lading to segfault

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#125]
PhysicsSystem is created in application.cpp and ScriptSystem is created in game_application.cpp
PhysicsSystem hits a segfault on hitting "close" button on the game/editor window

**Comment by IronicallySerious** [comment]
Move both of them in application.cpp in the correct order to fix this

**Comment by IronicallySerious** [comment]
I am picking this one up
