### ISSUE TITLE
Add basic mathematical capability in the GUI of transformComponent

### ISSUE THREAD

**Issue by CapriciousRebel** [sdslabs/Rootex#179]
A user must be able to enter basic mathematical expressions (addition/subtraction/multiplication/division) in the input boxes for transform component, and that expression must be evaluated and the result must be displayed, and updated.

**Comment by alexkarate** [comment]
I would like to work on this issue.

**Comment by IronicallySerious** [comment]
Very nice to hear that @alexkarate 

I have checked up on ImGui developers (ImGui is our GUI library for making the editor) that there is currently no easy way to add this functionality using only ImGui. 

However, there is still a way to do this, that they recommended. If we are able to hook up a Maths parser library to the engine then this would become much easier. We would just have to take the string that the user puts into the input box (after changing the input type to string input obviously), run it through the maths parser, and set the variables accordingly.

This would require some easy CMake stuff (almost copy-pasting the older CMake scripts) if you are able to find a header-only C++ math parsing library.

**Comment by silentC1C4D4** [comment]
I'd like to work on this issue.

**Comment by IronicallySerious** [comment]
@silentC1C4D4 Good to hear that. We hage later decided that this sort of a functionality is quite difficult to integrate at this point. I mean it is easy to write a maths parser or even integrate one but then you will have to replace all textboxes in the editor. And after discussion, we are fine with not having this feature as well

**Comment by silentC1C4D4** [comment]
@IronicallySerious  That's great!!

**Comment by IronicallySerious** [comment]
Decided as being too difficult for a niche feature as of now. Most of us working on Rootex are okay with using a calculator.
