### ISSUE TITLE
Scripting API standardization

### ISSUE THREAD

**Issue by IronicallySerious** [sdslabs/Rootex#270]
1. Ensure all Rootex API exists in `RTX` Lua table.

2. If some class is a singleton, then do not expose `GetSingleton()`. Make lambdas to call the function directly. This is a usability based suggestion. No idea if this is worse for performance or not.

	E.g.

	`RTX.EntityFactory.Get():openLevel(...)` ❌
	`RTX.EntityFactory.OpenLevel(...)` ✅

3. Try to enforce a way to make Lua event handlers to return values optionally. Not returning a `Variant` from a Lua function in the event of an `Event` current results in a stack error and shutdown of the script execution.

4. Find a better way to reference other entities and their scripts and the functions defined inside the scripts directly from the entity (like Godot?). If we go with the popular way to do this, we will likely end up with something that Godot and Unreal Engine do, where optionally a script can be bound to an entity, and the entity allows access to the script functions directly. 

	Although in the case of Godot the script is detachable and can be assigned to multiple nodes and in Unreal the script has to stay local to the entity and to have multiple instances of the script, you basically have to duplicate the entire entity blueprint (could cause files to bloat in our case unlike in Unreal, because we don't use entity classes to optimize instantiation time and space required while making duplicate entities).

	We currently are able to attach multiple scripts to an entity, which makes referencing a script and an entity harder.

5. Add a constructor and destructor to scripts.

6. Expose the script environment's global stuff (or stuff in a specific table?) to the editor so that those values can be altered and modified per `ScriptComponent` object. This means we will have to store "script value overrides" and assign them at construction time. This goes along with point 5. This will be harder to do with multiple scripts attached to 1 entity.

7. A way to call arbitrary functions on a script attached to an entity would be nice to have because it will also allow us to remove the hardcoded `onHit()` functions in the script.

**Comment by sin3point14** [comment]
How about something like a seperate namepace for every entity? the lua script won't have to refer it by namespace though. Script Component could do something like this-

```
Exposed Entities:
Lua Var Name          Entity ID
car                   Car #69
```
This namespace should be easy to store in a variable as Lua treats packages as tables
Then let's say that this `Car #69` has a script called driver.lua so we could refer it in our current script as-
```
car.driver.speed = 69
```

As for exposing variables, I tried some googling for lua reflection with comments or annotations. Couldn't find anything so I think a simple way could be to expose a table of variables having some default value attached to them. The name of the table would be fixed and type of variables can be found using reflection

```lua
expose = {
    speed = 69
    acceleration = 6.9
    driver_name = "Chad"
}
```

Then we can easily expose these values in the ImGui for `ScriptComponent`

**Comment by IronicallySerious** [comment]
@sin3point14 We can get the list of defined stuff inside a file with sol. So we can take all the non-functions out of that and expose them. But it is much better to have something like this export table

**Comment by IronicallySerious** [comment]
1. Entity and ScriptComponent need to be combined to allow `entity.scriptVariable` access.
2. Implement export table in whatever way discussed

**Comment by IronicallySerious** [comment]
Now fixed in master
