### ISSUE TITLE
Expose light selection radius from LightSystem

### ISSUE THREAD

**Issue by IronicallySerious** [sdslabs/Rootex#299]

**Comment by sin3point14** [comment]
but currently closest N lights are chosen where N can be configured so there isn't any point to this

**Comment by IronicallySerious** [comment]
@sin3point14 Yes, I meant we should expose this value to the editor and set this value per level

**Comment by IronicallySerious** [comment]
It's pretty reasonable to only do 4 dyn lights per scene. Closing this for now.
