### ISSUE TITLE
Shift local Lua API documentation in favor of the hosted version

### ISSUE THREAD

**Issue by ChronicallySerious** [sdslabs/Rootex#301]
I recently got this merged in RmlUi: https://mikke89.github.io/RmlUiDoc/pages/lua_manual/api_reference.html

So this means we don't need to maintain our own documentation in the editor. It is better hosted on the documentation site.

**Comment by IronicallySerious** [comment]
Will probably maintain a `.md` on the Lua API for this and let the docs website host it

**Comment by ChronicallySerious** [comment]
Since our API is always changing, it is best to keep the documentation as close to the binding code as possible. We also have the in-editor Lua API to supplement that.

However, for now, the best way to maintain this is to refer to this singular file

https://github.com/sdslabs/Rootex/blob/master/rootex/script/interpreter.cpp#L89
