### ISSUE TITLE
Fix SphereCollider

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#303]
Controls for the object having SphereCollider get stuck at times, jump never works

**Comment by sin3point14** [comment]
[tutorial.zip](https://github.com/sdslabs/Rootex/files/5311478/tutorial.zip) 
level files for testing, controls: WASD + space. sphere collider component on the Glass Collider entity sometimes gets stuck but no such issue occurs when box collider component is used

**Comment by IronicallySerious** [comment]
Sphere Collider was initially marked as available for sleep because Bullet wasn't expecting it to move in space after it has reached 0 velocity for a few seconds. Now kinematic bodies have been added which ignore this sleeping mechanic for colliders.
