### ISSUE TITLE
Convert diffuse, normal, specular map textures into texture arrays and upload them to GPU all at once

### ISSUE THREAD

**Issue by ChronicallySerious** [sdslabs/Rootex#313]

**Comment by IronicallySerious** [comment]
Needs more research on if doing this will ever help us

**Comment by ChronicallySerious** [comment]
Some textures, like the normal texture, just don't get uploaded in case the normals are disabled on a material. So there is very little need for this here.

Also, the new material refactor combined all the SRVs of these textures in a single array and the SRVs get set on the shader in a single call. So in terms of the actual need for doing this, we don't have it. Closing.
