### ISSUE TITLE
Add split string function

### ISSUE THREAD

**Issue by IronicallySerious** [sdslabs/Rootex#315]
Please. I regret opening this every time I want to split a string: https://stackoverflow.com/questions/275404/splitting-strings-in-c

**Comment by silentC1C4D4** [comment]
@IronicallySerious Can you assign this issue to me ?

**Comment by IronicallySerious** [comment]
@silentC1C4D4 You can go ahead and open PR. We assign people only for organizational purposes.

**Comment by IronicallySerious** [comment]
Now added in master
