### ISSUE TITLE
Fix bounding box orientation for animated models

### ISSUE THREAD

**Issue by Ishan-002** [sdslabs/Rootex#348]
Animated model is having its bounding boxes 90 degree rotated to model orientation. For now, this has been fixed by manually applying the required rotation to the bounding box calculation. But even after that, the model is not completely within the boundaries of the bounding box. 
<br>
![image (1)](https://user-images.githubusercontent.com/58972469/103592347-de297380-4f18-11eb-8bd4-d4aec944d94c.png)

This is since the actual scene root in the model file is not the root for animated model.

**Comment by ChronicallySerious** [comment]
This is largely the fault of the Assimp importer. We added some ways to mitigate this error e.g. pre rotating the bounding box, taking absolute extents in case the extents came out negative from Assimp (yes, this happens :/ ), but none of these is perfect.

The last way to fix this is to allow us to manually override bounding boxes on `TransformComponent`s, which made it into master recently :)
