### ISSUE TITLE
Cleanup Material system

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#378]
Material system is unclean and unintuitive in terms of adding new material to the engine. A new material class needs to be made inheriting Material, then it is to be registered in the MaterialLibrary, new shader class needs to be made, then it needs to be registered in ShaderLibrary, then new Vertex Buffers/Index Buffers need to be made and more things like that. This has a big scope of simplification.
Also, the current material overriding system feels unintuitive to use.

**Comment by ChronicallySerious** [comment]
Converted materials into resource files managed by the resource loader, made the different registrations separate so as to reduce clutter.

They are pretty clean as of now.

Also, removed ShaderLibrary and the need to inherit `Shader` when creating any new shader object. Had to make shaders compile dynamically for allowing this
