### ISSUE TITLE
Optimise default texture GPU binds

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#379]
Rootex supports a variety of textures like normal, specular, ambient etc. When an object's material doesn't use a type of texture, for example, normal texture(which is quite common for simple games), the GPU is supplied a default texture which doesn't affect the object's final colors. In the case of normal textures, it can be something like [this](https://filterforge.com/filters/14015-normal.jpg). Hence we don't need to rebind this texture for every object since a lot of them will be using the default texture and we can save a significant amount of bind calls.

**Comment by ChronicallySerious** [comment]
Using default texture for normals is not getting us any speed, which means having a bool which specifies if a normal exists or not is better for now
