### ISSUE TITLE
Disable LOD by default

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#522]
After practical usage, everyone prefers that LOD should be disabled by default

![image](https://user-images.githubusercontent.com/43549821/151679572-817587b9-5901-4297-aa93-3843daaad1c5.png)

**Comment by sin3point14** [comment]
Investigate if LOD is working fine

**Comment by Bisht13** [comment]
LOD is on by default, it is working fine, however right now one can set LOD distance and LOD bias to negative causing it to act in completely opposite way.
