### ISSUE TITLE
gameplay code in cpp?

### ISSUE THREAD

**Issue by ghost** [sdslabs/Rootex#608]
is it possible to code gameplay code such as player and other stuff in cpp?

**Comment by twaritwaikar** [comment]
Yes, we already do that for some things here - https://github.com/sdslabs/Rootex/blob/dev/rootex/framework/components/game/player_controller.cpp

It does require you to recompile the engine (doesn't take that long)

**Comment by ghost** [comment]
YES!!! lessgoo finally a engine that doesnt soly rely on lua or c# for gameplay (that isnt cryengine/ unreal)!
yea i understand you have to recompile engine but it is worth the performance gains and that's only language i know :)

**Comment by ghost** [comment]
also does it have networking yet?

**Comment by twaritwaikar** [comment]
No, no networking features in this engine. I don't think the crew plans to add any networking features to Rootex in the future. @r41k0u Is that still the case?

**Comment by r41k0u** [comment]
Not thinking of networking right now, we need to get this in a relatively bug free state before that
