### ISSUE TITLE
Add Anti-aliasing in editor viewport

### ISSUE THREAD

**Issue by IronicallySerious** [sdslabs/Rootex#62]
Anti-aliasing has been added to master, but only for when the game is being run. The anti-aliasing feature should also be tested with the editor for an easier workflow

**Comment by sin3point14** [comment]
Hasn't this been fixed @IronicallySerious ?

**Comment by IronicallySerious** [comment]
This is not fixed in master yet.

**Comment by IronicallySerious** [comment]
This was fixed on master somehow. Closing.
