### ISSUE TITLE
Lighting shenanigans

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#79]
![image](https://user-images.githubusercontent.com/43549821/77145423-87000280-6aae-11ea-89f6-4fcdbe0c7d70.png)
Lighting seems to be affecting non facing vertices
stolen from @IronicallySerious 
Please leave level files here

**Comment by IronicallySerious** [comment]
@sin3point14 This is the level
[spot_light_bug.zip](https://github.com/sdslabs/Rootex/files/4358767/spot_light_bug.zip)
