### ISSUE TITLE
OBJ file loading issue

### ISSUE THREAD

**Issue by sin3point14** [sdslabs/Rootex#80]
![image](https://user-images.githubusercontent.com/43549821/77145566-ed852080-6aae-11ea-8c40-15f4f1b27c9e.png)
This renders as this-
![image](https://user-images.githubusercontent.com/43549821/77145580-f7a71f00-6aae-11ea-9be6-6ad204af18a3.png)
again stolen from @IronicallySerious 
Please leave the obj and level files here

**Comment by IronicallySerious** [comment]
The object is this one https://free3d.com/3d-model/alien-animal-update-in-blender-28x-953251.html
Just add a new cube in am empty level and import this obj by providing the path in the Visual Model field

**Comment by IronicallySerious** [comment]
Fixed in #141
